### ISSUE TITLE
Multiple preconditions don't work as intendet

### ISSUE THREAD

**Issue by SasuP** [DbKeeperNet/DbKeeperNet#27]
in Updater.cs row 285 there is result &= currentresult;

If you have multiple preconditions and all fails, result will be true and not false as it should.

I think it should jump out on first currentresult=false is encountered and not continue.

**Comment by voloda** [comment]
Hi. Could you please let me know following:

* What preconditions (in which order) are you using
* What you mean by 'fails'- is it an exception or simply condition is not matched?

**Comment by voloda** [comment]
* The point that all preconditions are expected to return ```true``` - if any of them will return ```false``` the step should not be executed.
  * You may for example combine any condition with ```DbType``` one to make sure that the step will run only on single database type.

```xml
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Update engine table setup" Id="1">
      <Preconditions>
        <Precondition Precondition="UserNotFound">
          <Param>SomeUser</Param>
        </Precondition>
        <Precondition Precondition="UserNotFound">
          <Param>SomeUser2</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="dbMock">
        <![CDATA[query_to_be_executed_on_mock]]>
      </AlternativeStatement>
    </UpdateStep>
```
* The above ```query_to_be_executed_on_mock``` is expected to be run only if none of two users is found
* If you need to implemented opposite logic you can do so via a custom plugin and custom precondition implementation which should be pretty easy.

Let me know if you need some further guidance or help but to me it looks like it behaves as-desined.

**Comment by SasuP** [comment]
problem is basically on your db setup as all steps are marked notexecuted and other precondition is set for all steps, it always tries to setup those tables. If it would mark those steps, it would not try setup tables again.

**Comment by voloda** [comment]
Thanks. Would it be possible to share the setup xml? I'm still not clear on what can be wrong (which does not mean it is not actually wrong)

**Comment by SasuP** [comment]
I did mean those database setup.xlms which are build in dbkeepernet, sql server etc.

**Comment by voloda** [comment]
Are you saying that you cannot setup the database? Which version and database type?

**Comment by SasuP** [comment]
I can, but it runs dbkeeper setup xml everytime which is not needed.

**Comment by SasuP** [comment]
If i change it to markstep executed it works, but default is not to mark...

**Comment by voloda** [comment]
I see now - is that just confusing? 

I mean - it should, whenever the whole engine is executed evaluate all the steps whether those were or were not executed and those which were not should be applied (for the case you will add some step into older version).

Basically - those scripts are setting some system tables for tracking thus you cannot explicitely mark steps as executed and instead I have to evaluate the presence of the object in the database.

Does that make sense or am I not following your thougths properly still?

**Comment by SasuP** [comment]
why not mark, as it is assembly named, if you mark steps, it evaluates it correctly in second round, it doesn't infere to other assembly named versions as they are named to myassembly and not dbkeepernet.

**Comment by voloda** [comment]
Will you be able send your proposal as pull request? I will gladly accept it if that has benefits.

**Just few notes:**
* current scripts are written the way that I can perform upgrade easily in future as well
* on larger projects this has one more benefit - you can easily inject additional step to your previous DB upgrade (for example because of a bugfix) and it will still be correctly applied on all systems during the next execution

**Comment by voloda** [comment]
Btw. to your original proposal - I believe that in the end it works exactly as you proposed

**Comment by SasuP** [comment]
I'll be busy now with my project, but my project involves localization of dbkeepernet to Finnish and adding ms access support. Also how config is passed to dbkeeper will be changed so It has additional functions to pass real connectionstring, provider and setupfiles as I can't use current way of setting those. When finished I'll put changes to my github and share it with you, then you can take what ever change I have made as you see fit. I'll try not to change too much :)

**Comment by voloda** [comment]
Sounds like you have a lot of fun. I would suggest to introduce MS Access as an extension (I can guide you if needed) and will gladly accept any new/updated translations/enhancements as far as you will grant the project license for them :-).
